### ISSUE TITLE
Total as integer

### ISSUE THREAD

**Issue by llemonS** [inzamul36/Django-ROMS#1]
Prices can assume float values sometimes, the widthratio template are returning an integer value (line 50 from index.html) trying to fix but I dont know how. :(

Nice work!

**Comment by inzamul36** [comment]
Thanks for finding that mistake ......

Open this model file "Django-ROMS/orders/models.py" .  change this line "price = models.IntegerField()" to  "price = models.FloatField()" and migrate again....( delete your sqlite db file if not migrate )

**Comment by llemonS** [comment]
Did this, but hasn't solved. I've added a product with a value of 15.5 in price, and total is giving 16.
